/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.collegemanagementsystem;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
//import net.proteanit.sql.DbUtils;


public class Del extends javax.swing.JFrame {
 Connection con;
    ResultSet rs;
    Statement stmt1;
    PreparedStatement preStatement;
    int test=0;
    /**
     * Creates new form Del
     */
    public Del() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TButton = new javax.swing.JRadioButton();
        SButton = new javax.swing.JRadioButton();
        DButton = new javax.swing.JRadioButton();
        HButton = new javax.swing.JRadioButton();
        CButton = new javax.swing.JRadioButton();
        SubButton = new javax.swing.JRadioButton();
        DelButton = new javax.swing.JButton();
        Var1 = new javax.swing.JLabel();
        Field1 = new javax.swing.JTextField();
        Error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("What do you want to delete?");

        buttonGroup1.add(TButton);
        TButton.setText("Teacher");
        TButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(SButton);
        SButton.setText("Student");
        SButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(DButton);
        DButton.setText("Department");
        DButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(HButton);
        HButton.setText("HOD");
        HButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(CButton);
        CButton.setText("Course");
        CButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(SubButton);
        SubButton.setText("Subject");
        SubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubButtonActionPerformed(evt);
            }
        });

        DelButton.setText("Delete");
        DelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelButtonActionPerformed(evt);
            }
        });

        Field1.setVisible(false);

        Error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Error.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(DelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Var1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DButton)
                                        .addGap(49, 49, 49)
                                        .addComponent(Error, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(SButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(HButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(CButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(SubButton))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TButton)
                            .addComponent(SButton)
                            .addComponent(HButton)
                            .addComponent(CButton)
                            .addComponent(SubButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DButton)
                            .addComponent(Error, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addComponent(Var1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(DelButton)
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TButtonActionPerformed
        // TODO add your handling code here:
        Field1.setVisible(true);
        Var1.setText("Enter Pid of the Teacher: ");
    }//GEN-LAST:event_TButtonActionPerformed
    private void dbConnect() throws ClassNotFoundException, SQLException{
        String dbusername = "cms";
        String dbpassword = "vsa123";
        String dburl = "jdbc:oracle:thin:@localhost:1521:XE";
        Class.forName("oracle.jdbc.OracleDriver");  
        con=DriverManager.getConnection(dburl, dbusername, dbpassword);  
    }      
    private void DelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelButtonActionPerformed
        // TODO add your handling code here:
        if(TButton.isSelected()){
            try{
                dbConnect();
                String sql="Delete from Teacher where Pid = ?";
                preStatement = con.prepareStatement(sql);
                preStatement.setString(1,Field1.getText());
                preStatement.executeQuery();
                preStatement.close();
                String sql2="Delete from Person where Pid = ?";
                preStatement = con.prepareStatement(sql2);
                preStatement.setString(1,Field1.getText());
                preStatement.executeQuery();
                preStatement.close();
                String sql3="Delete from Employee where Pid = ?";
                preStatement = con.prepareStatement(sql3);
                preStatement.setString(1,Field1.getText());
                preStatement.executeQuery();
                preStatement.close();
                con.close();
                test=1;
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
            if(test==1){
                JOptionPane.showMessageDialog(this, "Record Deleted!");
                test=0;
            }
        }
        else if(SButton.isSelected()){
            try{
                dbConnect();
                String sql="Delete from Student where Pid = ?";
                preStatement = con.prepareStatement(sql);
                preStatement.setString(1,Field1.getText());
                preStatement.executeQuery();
                preStatement.close();
                String sql2="Delete from Person where Pid = ?";
                preStatement = con.prepareStatement(sql2);
                preStatement.setString(1,Field1.getText());
                preStatement.executeQuery();
                preStatement.close();
                con.close();
                test=1;
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
            if(test==1){
                JOptionPane.showMessageDialog(this, "Record Deleted!");
                test=0;
            }
        }   
        else if(HButton.isSelected()){
            try{
                dbConnect();
                String sql="Delete from HOD where Pid = ?";
                preStatement = con.prepareStatement(sql);
                preStatement.setString(1,Field1.getText());
                preStatement.executeQuery();
                preStatement.close();
                String sql2="Delete from Person where Pid = ?";
                preStatement = con.prepareStatement(sql2);
                preStatement.setString(1,Field1.getText());
                preStatement.executeQuery();
                preStatement.close();
                String sql3="Delete from Person where Pid = ?";
                preStatement = con.prepareStatement(sql3);
                preStatement.setString(1,Field1.getText());
                preStatement.executeQuery();
                preStatement.close();
                con.close();
                test=1;
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
            if(test==1){
                JOptionPane.showMessageDialog(this, "Record Deleted!");
                test=0;
            }
        }
        else if(CButton.isSelected()){
            try{
                dbConnect();
                String sql="Delete from Courses where Cid = ?";
                preStatement = con.prepareStatement(sql);
                preStatement.setString(1,Field1.getText());
                preStatement.executeUpdate();
                preStatement.close();
                con.close();
                test=1;
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
            if(test==1){
                JOptionPane.showMessageDialog(this, "Record Deleted!");
                test=0;
            }
        }
        else if(SubButton.isSelected()){
            try{
                dbConnect();
                String sql="Delete from Subjects where Subid = ?";
                preStatement = con.prepareStatement(sql);
                preStatement.setString(1,Field1.getText());
                preStatement.executeQuery();
                preStatement.close();
                con.close();
                test=1;
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this,ex);
            }
            if(test==1){
                JOptionPane.showMessageDialog(this, "Record Deleted!");
                test=0;
            }
        }
        else if(DButton.isSelected()){
            try{
                dbConnect();
                String sql="Delete from Department where Dno = ?";
                preStatement = con.prepareStatement(sql);
                preStatement.setString(1,Field1.getText());
                preStatement.executeQuery();
                preStatement.close();
                con.close();
                test=1;
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
            if(test==1){
                JOptionPane.showMessageDialog(this, "Record Deleted!");
                test=0;
            }
        }
        else{
            Error.setText("Select an option!");
        }
    }//GEN-LAST:event_DelButtonActionPerformed

    private void SButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SButtonActionPerformed
        // TODO add your handling code here:
        Var1.setText("Enter Pid of the Student: ");
        Field1.setVisible(true);
    }//GEN-LAST:event_SButtonActionPerformed

    private void HButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HButtonActionPerformed
        // TODO add your handling code here
        Var1.setText("Enter Pid of the HOD: ");
        Field1.setVisible(true);
    }//GEN-LAST:event_HButtonActionPerformed

    private void CButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CButtonActionPerformed
        // TODO add your handling code here:
        
        Var1.setText("Enter Cid of the Course: ");
        Field1.setVisible(true);
    }//GEN-LAST:event_CButtonActionPerformed

    private void SubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubButtonActionPerformed
        // TODO add your handling code here:
        Field1.setVisible(true);
        Var1.setText("Enter Sid of the Subject: ");
    }//GEN-LAST:event_SubButtonActionPerformed

    private void DButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DButtonActionPerformed
        // TODO add your handling code here:
        Field1.setVisible(true);
        Var1.setText("Enter Did of the Department: ");
    }//GEN-LAST:event_DButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EditingPage ep = new EditingPage();
        ep.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Del.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Del.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Del.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Del.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Del().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CButton;
    private javax.swing.JRadioButton DButton;
    private javax.swing.JButton DelButton;
    private javax.swing.JLabel Error;
    private javax.swing.JTextField Field1;
    private javax.swing.JRadioButton HButton;
    private javax.swing.JRadioButton SButton;
    private javax.swing.JRadioButton SubButton;
    private javax.swing.JRadioButton TButton;
    private javax.swing.JLabel Var1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
